server:
  port: 9201

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive # 解决和web包冲突问题
  application:
    name: learn-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: learn-api
          uri: lb://learn-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: learn-auth
          uri: lb://learn-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: learn-checkcode
          uri: lb://learn-checkcode
          predicates:
            - Path=/checkcode/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9202/rsa/publicKey #配置RSA的公钥访问地址
  redis:
    port: 6379
    host: localhost
    password:
  boot:
    admin:
      client:
        url: http://localhost:9401 #配置admin-server地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/auth/oauth/token"