server:
  port: 9202

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: learn-auth
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
  boot:
    admin:
      client:
        url: http://localhost:9401 #配置admin-server地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 20890  # dubbo服务暴露的端口
    registry:
      protocol: nacos
      address: 127.0.0.1:8848
    config-center:
      protocol: nacos
      address: 127.0.0.1:8848
    metadata-report:
      protocol: nacos
      address: 127.0.0.1:8848